mcguire: 
  build: ./boojpress
  ports:
    - "8001:80"
  volumes:
    - /data/wordpress/mcguire/:/var/www/wordpress/wp-content/uploads/
  environment:
    - WP_DB_USER=root
    - WP_DB_NAME=blog_mcguire
    - WP_THEME=mcGuire2
    - WP_DB_HOST=db1.local:3306   
  links:
    - mysql:db1.local

ebby: 
  build: ./boojpress
  ports:
    - "8002:80"
  volumes:
    - /data/wordpress/ebby/:/var/www/wordpress/wp-content/uploads/
  environment:
    - WP_DB_USER=root
    - WP_DB_NAME=blog_ebby
    - WP_THEME=ebby
    - WP_DB_HOST=db1.local:3306
  links:
    - mysql:db1.local

mysql: 
  build: ./mysql
  ports:
  - "3308:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=cleancut
    - MYSQL_USER=wpadmin
    - MYSQL_PASSWORD=cleancut

